config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'artists/:id' => "artists#show", :as=> "artist"

  get 'songs/search'

  get 'braim_test' => "recommendations#test", as: 'test'

  get 'recommendations' =>"recommendations#index",as: "recommendations"

  get 'discover' =>"songs#discover",as: "discover"

  get 'songs/:id'=> "songs#show", :as => "song"

  post 'songs/rate'=> "songs#rate", :as => "song_rate"

  get 'QuickDeal' => "songs#deal", :as =>"deal"

  post 'recordings/create' =>  "recordings#create" 

  get 'recordings/show_data' =>  "recordings#show_data" 

  get 'recordings/show' =>  "recordings#show" 

  get 'recordings/index' =>  "recordings#index" 

  match "recordings/destroy", to: "recordings#destroy", via: :delete
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  authenticated :user do
    root :to => "songs#search" , :as => "authenticated_root"
  end
  root to: 'visitors#home'
  get "/about" => "visitors#about"
  get "/scroll/:scroll_id" => "users#scroll", as: "scroll"
  get '/profile' => "users#profile"
  get "/performance" => "users#performance"
  get "/headset" =>  "users#headset" 
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#  last_name              :string
#  country                :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile, dependent: :destroy

  has_many :ratings
  has_many :songs, :through => :ratings
  has_many :recordings
  
  accepts_nested_attributes_for :profile

  def recordings_min
    recordings.where("duration >= ?", 29)#.collect{ |recording| recording.song}
  end

  def recorded_songs
    recordings_min.collect{ |recording| recording.song}
  end
  
  def full_name
    (self.name || "").capitalize
  end
  
  def country_name
    country = ISO3166::Country[self.country]
    country ? country.translations[I18n.locale.to_s].capitalize : ""
  end
  # def save_and_index
  #   if self.save
  #     user_info = {'email'=> self.email, 'name'=> self.name, 'last_name'=> self.last_name, 'country'=> self.country}
  #     profile_info = {}
  #     profile_info = {'birthday'=>self.profile.birthday,'gender'=>self.profile.gender} if self.profile
  #     request = PIO_CLIENT.create_event(
  #       '$set',
  #       'user',
  #       self.id,
  #       { 'properties' => user_info.merge(profile_info)}
  #     )
  #     return JSON.parse(request.body)['eventId']
  #   else
  #     return false
  #   end
  # end
  def save_prediction_info
   user_info = {'email'=> self.email, 'name'=> self.name, 'last_name'=> self.last_name, 'country'=> self.country}
    profile_info = {}
    profile_info = {'birthday'=>self.profile.birthday,'gender'=>self.profile.gender} if self.profile
    request = PioClient.create_event(
      '$set',
      'user',
      self.id,
      { 'properties' => user_info.merge(profile_info)}
    )
    return JSON.parse(request.body)['eventId']
  end
  validates :name , presence: true
  validates :last_name , presence: true
  validates :country , presence: true


  def neighborhood
    Neighborhood.new(self)
  end

  def neighborhood_affective(state,mode)
    NeighborhoodAffective.new(self,state,mode)
  end

  def neighborhood_increments(state)
    NeighborhoodIncrements.new(self,state)
  end

  def recommendations_increments(state)
    colab_filtering = ColabFilteringIncrements.new(self,state)
    unknown_songs = Song.all - songs
    recommendation_list = []
    unknown_songs.each do |song|
      score = colab_filtering.prediction(song)
      #byebug
      if score
        recommendation_list << Prediction.new(song,score)
        #byebug
      end
    end
    recommendation_list.sort_by(&:score).reverse
  end

  def recommendations_affective(state,mode)
    colab_filtering = ColabFilteringAffective.new(self, state,mode)
    unknown_songs = Song.all - songs
    recommendation_list = []
    unknown_songs.each do |song|
      score = colab_filtering.prediction(song)
      #byebug
      if score
        recommendation_list << Prediction.new(song,score)
        #byebug
      end
    end
    recommendation_list.sort_by(&:score).reverse
  end

  def recommendations
    colab_filtering = ColabFiltering.new(self)
    unknown_songs = Song.all - songs
    recommendation_list = []
    unknown_songs.each do |song|
      score = colab_filtering.prediction(song)
      #byebug
      if score
        recommendation_list << Prediction.new(song,score)
        #byebug
      end
    end
    recommendation_list.sort_by(&:score).reverse
  end

  def rating_average
    if ratings.any?
      ratings.inject(0){ |sum, n| sum + n.value}.to_f / ratings.size 
    else
      0.0
    end
  end
  
end

app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#  last_name              :string
#  country                :string
#

require 'elasticsearch'

class UsersController < ApplicationController

  before_action :authenticate_user!

  def profile
    @user = current_user
    @recordings = @user.recordings.order(created_at: :desc)
  end

  def scroll
    client = Elasticsearch::Client.new log: true
    response = client.scroll(scroll: '5m', scroll_id: params[:scroll_id])['hits']['hits']
    response.delete_if{|x| x['_source']['song_id']==nil}
    songs_ids = response.collect {|r| r['_source']['song_id']}
    @songs = RSpotify::Track.find(songs_ids)
    @recordings = response.map do |r| 
      current_song = @songs.select {|song| song.id == r['_source']['song_id'] }
      r['song_info'] = current_song[0]
      r
    end
    respond_to do |format|
      format.js { render :template => '/users/scroll'}
    end
  end
end

app/helpers/users_helper.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#  last_name              :string
#  country                :string
#

module UsersHelper
  def spotify_image_tag(item)
    if item.images.any? 
      image_tag item.images.first["url"] , class: "lib-img-show artist-image" 
    else
      image_tag "default-image.png", class: "lib-img-show artist-image" 
    end
  end
end

app/views/users/_headset.html.haml
.headset-container
  #headset
    #headset-img
      =image_tag "headset/headset.png"
    #f3
      =image_tag "headset/f3-black.png" ,:name => "smallNote"
    #f4
      =image_tag "headset/f4-black.png",:name => "smallNote"
    #t7
      =image_tag "headset/t7-black.png",:name => "smallNote"
    #t8
      =image_tag "headset/t8-black.png",:name => "smallNote"
    #pz
      =image_tag "headset/pz-black.png",:name => "smallNote"
        
      

app/views/users/_query_results.html.haml
-@recordings.each_with_index do |recording, i|
  %tr
    %th
      =link_to "#" ,class: "show-graph-btn", "data-rec-id"=>"#{recording['_id']}" do
        =image_tag "graph_preview.jpg",class: "graph-preview"
    %th 
      %p
        =Date.strptime((recording['_source']['date']/1000).to_s,'%s')
    %th 
      = audio_tag recording['song_info'].preview_url, class: "audio-play"
      =link_to "#", class: "btn btn-link audioButton" do
        .glyphicon.glyphicon-play
    %th{:scope => "row"}
      =recording['song_info'].name
    %td
      %p 
        =recording['song_info'].album.name
    %td
      .album-track-query
        =spotify_image_tag recording['song_info'].album
    %td
      %p
        =Time.at(recording['song_info'].duration_ms/1000).utc.strftime("%M:%S")
    %td
      =link_to song_path(recording['song_info'].id), class: "btn btn-default loading-button" do
        %i
        %span
          Song Profile

app/views/users/_signal_description.html.haml
.box_description
  .title_box.c11
    %h4 Setup Steps
  .tabs_step
    %h1 Headset Setup Guide
    %span.stepGuide Step 1
    %br/
    Before putting on the Emotiv headset, ensure that each of the 16 electrode recesses are fitted with a moist felt pad.
    If the pads are not already moist, wet them with saline solution before inserting into the headset,
    or, alternatively, use a medicine dropper to carefully moisten the pads while already in place.
    %br/
    %br/
    %span.stepGuide Step 2
    Switch on the Emotiv headset and verify that the built-in battery is charged and is providing power by looking for the blue LED located near the power switch at the back of the headset.
    If the headset battery needs charging then set the power switch to the off position and plug the headset into the Emotiv battery charger using the mini-USB cable provided with the headset.
    Allow the headset battery to charge for at least 15 minutes before trying again.
    %br/
    %br/
    %span.stepGuide Step 3
    Verify that the Wireless Signal reception is reported as Good by looking at the Engine Status box in the Emotiv Control Panel.
    If it is not, make sure that the Emotiv Dongle is inserted into a USB port on your computer and that the single LED on the top half of the
    dongle is on continuously or flickering very rapidly.  If the LED is blinking slowly or is not illuminated, then remove the dongle from the
    computer, reinsert it, and try again.  Remove any metallic or dense physical obstructions located near the dongle or the headset, and move away
    from any powerful sources of electromagnetic interference, such as microwave ovens or high-powered radio transmitters.
    %br/
    %br/
    %span.stepGuide Step 4
    Put on the Emotiv headset by gently pulling apart the headband and lowering the sensor arms onto your head from the top down,
    near the rear of the skull.  Next, slide the headset forward until the sensors closest to the headset pivot points are located
    directly above your ears and as close to your hairline as possible.  Adjust the fit so that the rectangular compartments at the front
    ends of the headband sit comfortably just above and behind your ears.  Tilt the headset so that the two lowest, frontmost sensors are
    symmetric on your forehead and positioned 2 to 2.5 inches above your eyebrows.  Finally, check that all sensors are touching your head and,
    if not,  then fine tune the headset fit by gently sliding the headset in small increments until an ideal fit has been achieved.
    %br/
    %br/
    %span.stepGuide Step 5
    The Headset Setup tab in Emotiv Control Panel shows a top-down view of the Emotiv headset sensor array.  The contact quality of each sensor
    is represented by a color code:
    %br/
    %br/
    %label{:style => "font-weight:bold"}
      %span{:style => "padding-left:40px"} Black
    %span{:style => "padding-left:40px"}
      No signal
      %br/
      %br/
      %label{:style => "font-weight:bold;color:red"}
        %span{:style => "padding-left:40px"} Red
      %span{:style => "padding-left:50px"}
        Very poor signal
        %br/
        %br/
        %label{:style => "font-weight:bold;color:orange"}
          %span{:style => "padding-left:40px"} Orange
        %span{:style => "padding-left:25px"}
          Poor signal
          %br/
          %br/
          %label{:style => "font-weight:bold;color:yellow"}
            %span{:style => "padding-left:40px"} Yellow
          %span{:style => "padding-left:30px"}
            Fair signal
            %br/
            %br/
            %label{:style => "font-weight:bold;color:green"}
              %span{:style => "padding-left:40px"} Green
            %span{:style => "padding-left:30px"}
              Good signal
              %br/
              %br/
              %span.stepGuide Step 6
              Starting with the two sensors just above and behind your ears (these are reference sensors for which good contact with your scalp is essential), adjust the sensors so they make proper contact with your scalp
              (i.e. show green on the contact quality display). If the indicators are:
              %br/
              %span{:style => "padding-left:40px"}
                %label{:style => "font-weight:bold"} Black:
                Check that the sensor has a felt pad fitted.  Check that the felt pad is pressing firmly against your scalp.
                Then try re-moistening the felt pad.  If this problem persists, this may indicate a problem with the Emotiv headset.
                %br/
                %span{:style => "padding-left:40px"}
                  %label{:style => "font-weight:bold"} Yellow,Orange,Red:
                  The sensor is not making good contact with your scalp.  Check that the felt pad is making comfortable but firm contact with your scalp.
                  If the contact is adequate, ensure that the felt pad is moist.  If the sensor's indicator color becomes lighter, the signal quality is
                  improving.  If the sensor's indicator color is getting darker, the signal quality is deteriorating.  If problems still persist, try parting
                  the hair in the vicinity of the electrode so the felt pad makes better contact with your scalp.
                  %br/
                  %br/
                  %span.stepGuide Step 7
                  Repeat Step 6 for each of the remaining electrodes until all the sensors have adequate contact quality.
                  Although the majority of indicators should display green, the Emotiv detections will usually tolerate input from up to several
                  sensors whose indicators display yellow.
                  %br/
                  %br/
                  %label{:style => "font-weight:bold"}
                    If at any time the reference sensors (located just above and behind your ears) no longer have a good connection (i.e. are not showing green),
                    immediately restore those sensors to green before proceeding further.

app/views/users/_signal_level.html.haml
#signal-level
  %ul
    %li
      =image_tag "headset/good.png"
      %p Good
    %li
      =image_tag "headset/poor.png"
      %p Poor
    %li
      =image_tag "headset/bad.png"
      %p Bad
    %li 
      =image_tag "headset/no-signal.png"
      %p No signal

app/views/users/headset.html.haml
%h1 Headset
.row
  .col-sm-7
    =render "headset"
  .col-sm-5
    =render "signal_level"
.row
  =render "signal_description"
/ /#page-content-wrapper
/ /#wrapper
/ Menu Toggle Script
:javascript
  $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
  });

app/views/users/performance.html.haml
=javascript_include_tag "performance/performance"
%h1 Performance Metrics
#container{:style => "min-width: 310px; height: 400px; margin: 0 auto"}
.performance-info
  .col-xs-12.performance-info-content
    %p.info-performance-title Performance Metrics
    %p Control Panel shows a real time graph of cognitive performance as measured by 6 key metrics:
  .col-xs-12.performance-info-content
    %span.info-title Interest
    =image_tag "performance/interest-color.png"
    %p Interest is a measure of your enjoyment of the activity. Mid range scoring means that the task is informative in nature but does not have high emotional content.
  .col-xs-12.performance-info-content
    %span.info-title Engagement
    =image_tag "performance/engagement-color.png"
    %p Engagement is your level of immersion while performing the activity. High engagement levels ensure better retention of information.
  .col-xs-12.performance-info-content
    %span.info-title Focus
    =image_tag "performance/stress-color.png"
    %p Focus is a ability to perform individual task with consistent, sustained levels of concentration.
  .col-xs-12.performance-info-content
    %span.info-title Relaxation
    =image_tag "performance/relaxation-color.png"
    %p Relaxation is your ability to switch of and allow yoursefl to rest and recover from intense concentration. Finding time to relax throughout the day is beneficial to your health.
  .col-xs-12.performance-info-content
    %span.info-title Stress
    =image_tag "performance/stress-color.png"
    %p Stress is measure of your level of comfort with the current challenge. Short term stress improves productivity but sustained long term stress is destructive to your well-being.
  .col-xs-12.performance-info-content
    %span.info-title Instantaneous Excitement
    =image_tag "performance/instaneous-excitement-color.png"
    %p Excitement is related to the degree of emotional intensity or arousal in the current activity. Instantaneous Excitement plots short term changes in excitement levels, such as when you are startled.
  .col-xs-12.performance-info-content
    %span.info-title Long Term Excitement
    =image_tag "performance/long-term-excitement-color.png"
    %p Excitement is related to the degree of emotional intensity or arousal in the current activity. Long Term Excitement is calibrated to the ranges detected in your individual excitement levels, and helps you identify trends over time.

app/views/users/profile.html.haml
=javascript_include_tag "performance/performance"
.container-fluid
  .row.user-menu-container.square
    .col-md-12.user-details
      .row.coralbg.white
        .col-md-8.no-pad
          .user-pad
            %h3 
              Welcome back,
              =@user.full_name
            %h4.white
              %i.fa.fa-check-circle-o
              =@user.country_name
              
            =link_to edit_user_registration_path, class: "btn btn-labeled btn-info" do 
              %span.btn-label
                %i.fa.fa-pencil
              Update
        .col-md-4.no-pad
          .user-image
            =image_tag gravatar_url(@user), class: "img-responsive thumbnail"
            
      .row.overview
        .col-md-4.user-pad.text-center
          %h3 RECORDINGS
          %h4
            =@recordings.count
        .col-md-4.user-pad.text-center
          %h3 FOLLOWERS
          %h4 0
        .col-md-4.user-pad.text-center
          %h3 FOLLOWING
          %h4 0
  %h2 Last song recordings
  .tab-content
    #songs_tab.tab-pane.active{:role => "tabpanel"} 
      %table.table
        %thead
          %tr
            %th Graph
            %th Date
            %th Preview
            %th Name
            %th Album
            %th Cover
            %th Duration
            %th Score (Excitement)
            %th
        %tbody#tab_body
          -@recordings.each_with_index do |recording, i|
            %tr
              %th
                =link_to "#" ,class: "show-graph-btn", "data-rec-id"=>"#{recording.id}" do
                  =image_tag "graph_preview.jpg",class: "graph-preview" 
              %th 
                %p
                  =recording.date.to_s
              %th 
                = audio_tag recording.song.preview_url, class: "audio-play"
                =link_to "#", class: "btn btn-link audioButton" do
                  .glyphicon.glyphicon-play
              %th{:scope => "row"}
                =recording.song.name
              %td
                %p 
                  =recording.song.album_name
              %td
                .album-track-query
                  =image_tag recording.song.album_cover_url
              %td
                %p
                  =#Time.at(recording['song_info'].duration_ms/1000).utc.strftime("%M:%S")
                  ="#{recording.duration} s"
              %td
                %p
                  =recording.increments_counter("instantaneousExcitement")
              %td
                =link_to song_path(recording.song.song_spotify_id), class: "btn btn-default loading-button" do
                  %i
                  %span
                    Song Profile
  #ajax_message Loading Recordings ...
  =#link_to "Show older recordings", scroll_path(@scroll_id), id: "#more_recordings", remote: true if @recordings.any?

#graph_modal.modal.fade{:role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4.modal-title Recording Graph
      .modal-body
        #grap_container{:style => "min-width: 650px; height: 300px; margin: 0 auto"}
        %p#modal-message Loading Graph
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close