config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'artists/:id' => "artists#show", :as=> "artist"

  get 'songs/search'

  get 'braim_test' => "recommendations#test", as: 'test'

  get 'recommendations' =>"recommendations#index",as: "recommendations"

  get 'discover' =>"songs#discover",as: "discover"

  get 'songs/:id'=> "songs#show", :as => "song"

  post 'songs/rate'=> "songs#rate", :as => "song_rate"

  get 'QuickDeal' => "songs#deal", :as =>"deal"

  post 'recordings/create' =>  "recordings#create" 

  get 'recordings/show_data' =>  "recordings#show_data" 

  get 'recordings/show' =>  "recordings#show" 

  get 'recordings/index' =>  "recordings#index" 

  match "recordings/destroy", to: "recordings#destroy", via: :delete
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  authenticated :user do
    root :to => "songs#search" , :as => "authenticated_root"
  end
  root to: 'visitors#home'
  get "/about" => "visitors#about"
  get "/scroll/:scroll_id" => "users#scroll", as: "scroll"
  get '/profile' => "users#profile"
  get "/performance" => "users#performance"
  get "/headset" =>  "users#headset" 
end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id                        :integer          not null, primary key
#  song_spotify_id           :string
#  song_spotify_url          :string
#  name                      :string
#  preview_url               :string
#  album_cover_url           :string
#  album_name                :string
#  duration                  :integer
#  artist_name               :string
#  artist_spotify_id         :string
#  echonest_song_type        :string           is an Array
#  echonest_key              :integer
#  echonest_energy           :float
#  echonest_liveness         :float
#  echonest_tempo            :float
#  echonest_speechiness      :float
#  echonest_acousticness     :float
#  echonest_instrumentalness :float
#  echonest_mode             :integer
#  echonest_time_signature   :integer
#  echonest_loudness         :float
#  echonest_valence          :float
#  echonest_danceability     :float
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  echonest_id               :string
#

class Song < ActiveRecord::Base
  has_many :ratings
  has_many :users, :through => :ratings
  has_many :recordings
  
  def last_recording
    recordings.last
  end
  
  def self.songs_to_discover(user)
    recordings = Recording.all_except(user)
    songs = recordings.collect{|r| r.song}
    discover_songs = songs.uniq
    user_recordings = user.recordings
    user_songs = user_recordings.collect{|r| r.song}
    user_songs.each do |user_song| 
      discover_songs.delete_if {|song| song == user_song}
    end
    discover_songs
  end
  def self.register_from_echonest(echonest_id)
    song = Song.find_by(echonest_id: echonest_id)
    if song == nil 
      song_profile = Echowrap.song_profile(id:echonest_id, bucket: ['id:spotify','tracks','audio_summary','song_type'],limit:true)
      if song_profile
        new_song_id = song_profile.tracks[0].foreign_id.split('spotify:track:')[1]
        Song.find_or_register(new_song_id,echonest_id,song_profile)
      end
    end
  end
  def self.find_or_register(query_id,echonest_id=nil,song_profile=nil)
    song = Song.find_by(song_spotify_id: query_id)
    if song
      return song
    else
      song = SongApi.get_song_from_apis(query_id,echonest_id,song_profile)
      song.save_prediction_info
      return song
    end
  end
   def get_rating(current_user)
    rating = ratings.find_by(user: current_user)
    if rating 
      return rating.value
    else
      return 0
    end
  end
  def save_prediction_info
    song_info = self.attributes
    song_info.delete('id')
    request = PioClient.create_event(
      '$set',
      'item',
      self.id,
      { 'properties' => song_info.stringify_keys}
    )
    return JSON.parse(request.body)['eventId']
  end
end

app/controllers/songs_controller.rb
# == Schema Information
#
# Table name: songs
#
#  id                        :integer          not null, primary key
#  song_spotify_id           :string
#  song_spotify_url          :string
#  name                      :string
#  preview_url               :string
#  album_cover_url           :string
#  album_name                :string
#  duration                  :integer
#  artist_name               :string
#  artist_spotify_id         :string
#  echonest_song_type        :string           is an Array
#  echonest_key              :integer
#  echonest_energy           :float
#  echonest_liveness         :float
#  echonest_tempo            :float
#  echonest_speechiness      :float
#  echonest_acousticness     :float
#  echonest_instrumentalness :float
#  echonest_mode             :integer
#  echonest_time_signature   :integer
#  echonest_loudness         :float
#  echonest_valence          :float
#  echonest_danceability     :float
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  echonest_id               :string
#

require 'rspotify'
class SongsController < ApplicationController
  before_action :authenticate_user!
  def search
    if params[:query]
      #@songs =  Echowrap.song_search(title: params[:query], results:20, bucket: 'song_type', sort: "artist_hotttnesss-desc")
      #@artists = Echowrap.artist_search(name: 'juanes', results:1, bucket: ['artist_location','images','genre'])
      @songs = RSpotify::Track.search(params[:query],limit:20)
      @artists = RSpotify::Artist.search(params[:query],limit:5)
    end
    respond_to do |format|
      format.html 
      format.js { render :template => '/songs/search'}
    end
  end

  def rate
    id = params[:song_id]
    value = params[:rating]
    song = Song.find(id)
    current_rating = song.ratings.find_by(user: current_user)
    if current_rating
      current_rating.value = value
      current_rating.save
    else
      current_rating = song.ratings.create(user: current_user, value: value)
    end
    current_rating.save_prediction_info
    #byebug
    respond_to do |format|
      format.any { render json: {response: 'ok',rating: value}, content_type: 'application/json' }
    end
  end

  def show
    @song = Song.find_or_register(params[:id])
    @user = current_user
    @rating =@song.get_rating(@user)
    #byebug
    @recordings = @song.recordings.where(user: @user).order(created_at: :desc)
    #@recordings = Recording.all query: {bool: { must: [{ match: { user_id: @user.id}},{match: {song_id: @song.song_spotify_id}}]}},sort: [
    #  {date: {order: "desc", mode: "avg"}}]
  end

  def license
    respond_to do |format|
      format.any { render json: {response: 'ok','License' => "EEG"}, content_type: 'application/json' }
    end
  end
  def discover
    @songs = Song.songs_to_discover(current_user).shuffle
  end
end

app/helpers/songs_helper.rb
# == Schema Information
#
# Table name: songs
#
#  id                        :integer          not null, primary key
#  song_spotify_id           :string
#  song_spotify_url          :string
#  name                      :string
#  preview_url               :string
#  album_cover_url           :string
#  album_name                :string
#  duration                  :integer
#  artist_name               :string
#  artist_spotify_id         :string
#  echonest_song_type        :string           is an Array
#  echonest_key              :integer
#  echonest_energy           :float
#  echonest_liveness         :float
#  echonest_tempo            :float
#  echonest_speechiness      :float
#  echonest_acousticness     :float
#  echonest_instrumentalness :float
#  echonest_mode             :integer
#  echonest_time_signature   :integer
#  echonest_loudness         :float
#  echonest_valence          :float
#  echonest_danceability     :float
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  echonest_id               :string
#

module SongsHelper
end

app/views/songs/_query_results.html.haml
-if query
  %div
    / Nav tabs
    %h3
      ="Results for '#{query}'"
    %ul.nav.nav-tabs{:role => "tablist"}
      %li.active{:role => "presentation"}
        %a{"aria-controls" => "songs_tab", "data-toggle" => "tab", :href => "#songs_tab", :role => "tab"} 
          ="#{songs.size} Songs found"
      %li{:role => "presentation"}
        %a{"aria-controls" => "artists_tab", "data-toggle" => "tab", :href => "#artists_tab", :role => "tab"}
          ="#{artists.size} Artists found"
    / Tab panes
    .tab-content
      #songs_tab.tab-pane.active{:role => "tabpanel"} 
        %table.table
          %thead
            %tr
              %th Preview
              %th Song Name
              %th Artist
              %th Album Name
              %th Album Cover
              %th Duration
              %th 
          %tbody
            -songs.each_with_index do |song, i|
              %tr
                %th 
                  =audio_tag song.preview_url, class: "audio-play"
                  =link_to "#", class: "btn btn-link audioButton" do
                    .glyphicon.glyphicon-play
                  
                %th{:scope => "row"}
                  =song.name
                %th
                  =link_to song.artists.first.name ,artist_path(song.artists.first.id) ,class: "loading-link" if song.artists.any? 
                %td
                  %p 
                    =song.album.name
                %td
                  .album-track-query
                    =spotify_image_tag song.album
                %td
                  %p
                    =Time.at(song.duration_ms/1000).utc.strftime("%M:%S")
                %td
                  =link_to song_path(song.id), class: "btn btn-default loading-button" do
                    %i
                    %span
                      Song Profile



      #artists_tab.tab-pane{:role => "tabpanel"} 
        .container-fluid
          %br
          .row
            -artists.each_with_index do |artist, i|
              .col-md-6
                =link_to artist_path(artist.id) ,class: "loading-button"do
                  .artist-query-container.no-padding.lib-item{"data-category" => "view"}
                    .lib-panel
                      .row.box-shadow
                        .col-md-6
                          =spotify_image_tag artist
                        .col-md-6
                          .lib-row.lib-header
                            =artist.name
                            .lib-header-seperator
                          .lib-row.lib-desc
                            %p.artist-followers-query
                              %strong Spotify Followers:
                              %span
                                =artist.followers["total"]
                          




            

app/views/songs/_save_recording_modal.html.haml
#save_recording_modal.modal.fade{:role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4.modal-title Save Performance Metrics Recording
      .modal-body
        %p Are you sure to save this recording?
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Keep Recording
        %button.btn.btn-danger#cancel_recording_button{:type => "button"} Discard Recording
        %button.btn.btn-success#save_recording_button{:type => "button"} Save Recording

app/views/songs/discover.html.haml
%section#discoverSongs
  %h1 See what other Braim users are listening
  .container-fluid
    .row
      -@songs.each do |song|
        .col-sm-6
          =link_to song_path(song.song_spotify_id) do
            .discover-song
              =image_tag song.album_cover_url , class: "discover-song-image"
              .discover-song-info
                ="#{song.name} - #{song.artist_name}"
              %br
              %strong Last recording:
              .discover-song-last-user
                =image_tag gravatar_url(song.last_recording.user), class: "img-responsive mini-thumb"
                =song.last_recording.user.full_name
                ="at: #{song.last_recording.created_at.strftime("%d %B")}"
              

              
      

app/views/songs/search.html.haml
%section.search-song-section
  #search-box.jumbotron
    %h2 Search Music
    .search-songs-form
      =form_tag songs_search_path, method: :get , id: "search_songs_form" ,remote: true do 
        .input-group
          =text_field_tag :query, params[:query], class: "form-control" , placeholder: "Song title or Artist name..."
          %span.input-group-btn
            =button_tag name: nil , class: "btn btn-default search-button" ,type: "submit"do
              %i
              %span Search
  #songs_list
    =render partial: "query_results" , locals: {songs: @songs, artists: @artists, query: params[:query]}
        
      

app/views/songs/show.html.haml
=javascript_include_tag "performance/performance"
#song.container-fluid
  %section#song-info{"data-song-id"=>"#{@song.id}","data-user-id"=>"#{current_user.id}"}
  .song-title
    %h2.title
      =@song.name
      %span
      =" - #{@song.artist_name}"
  .song-content
    .row
      .col-md-5
        %iframe#app-player{:allowtransparency => "true", :frameborder => "0", :height => "380", :src => "https://embed.spotify.com/?uri=#{@song.song_spotify_url}", :width => "100%"}
      .col-md-7
        %h3 Song Info
        %p
          %strong Duration:
          %span
            =Time.at(@song.duration/1000).utc.strftime("%M:%S")
        %p
          %strong Album:
          %span
            =@song.album_name
        -if @song.echonest_song_type
          %p
            %strong Song type:
            %span
              -@song.echonest_song_type.each do |tag|
                =tag

          %h3 Audio Summary
          .row
            .col-md-6
              %p
                %strong Energy:
                %span
                  =@song.echonest_energy
              %p
                %strong Liveness:
                %span
                  =@song.echonest_liveness
              %p
                %strong Tempo:
                %span
                  =@song.echonest_tempo
              %p
                %strong Speechiness:
                %span
                  =@song.echonest_speechiness
              %p
                %strong Acousticness:
                %span
                  =@song.echonest_acousticness
            .col-md-6
              %p
                %strong Instrumentalness:
                %span
                  =@song.echonest_instrumentalness
              %p
                %strong Time signature:
                %span
                  =@song.echonest_tempo
              %p
                %strong Loudness:
                %span
                  =@song.echonest_loudness
              %p
                %strong Valence:
                %span
                  =@song.echonest_valence
              %p
                %strong Danceability:
                %span
                  =@song.echonest_danceability
        %h3 My rating for this song
        #stars.starrr{"data-rating" => "#{@rating}"}
        You gave a rating of
        %span#count
          =@rating
        star(s)
        / .row.lead
        /   %p Also you can give a default rating by adding attribute data-rating
        /   #stars-existing.starrr{"data-rating" => "4"}
        /   You gave a rating of
        /   %span#count-existing 4
        /   star(s)

  .song-insight-records
    %h3 Emotiv Performance Metrics
    .record-data.text-center
      .emotion.interest
        %strong Interest
      .emotion.engagement
        %strong Engagement/Boredom
      .emotion.focus
        %strong Focus
      .emotion.relaxation
        %strong Relaxation
      .emotion.inst-excitement
        %strong Instantaneous Excitement
      .emotion.long-excitement
        %strong Long Term Excitement
      .emotion.stress
        %strong Stress
    #container{:style => "min-width: 310px; height: 100px; margin: 0 auto"}
    %br
    .record-buttons
      %h4 Press to record:
      =link_to  "#", class: "btn btn-danger btn-record",id: "record_performance_button", "data-song-id"=>@song.id,"data-song-duration"=>@song.duration , "data-user-id"=>@user.id do
        .glyphicon.glyphicon-record
      =link_to "#", class: "btn btn-primary disabled btn-record",id: "stop_record_performance_button" do
        .glyphicon.glyphicon-stop
      %span#record_message 
        %span Recording... Time:
        %span#message_time 0
        %span 
          ="Max Duration: #{Time.at(@song.duration/1000).utc.strftime("%M:%S")}"

    %h3.text-center.recorgins-title My recordings
    -if @recordings
      #song_recordings
        -@recordings.each do |r|
          .notice.notice-lg.recording
            =link_to "x", "#", class: "delete-recording" , "data-recording-id" => r.id
            %h4 
              =(r.date).strftime("Recording at %B %d %Y, %l:%M:%S %P")
              = ", Duration: #{r.duration} s"
            %div{id:"#{r.id}"}
            =link_to "View Graph" , "#", "data-recording-id"=>r.id , class: "graph-data-link"
    =#link_to "Show older recordings", "#", id:"older_song_recordings"
    
  #dialog_delete_recording
  =render "save_recording_modal"