config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'artists/:id' => "artists#show", :as=> "artist"

  get 'songs/search'

  get 'braim_test' => "recommendations#test", as: 'test'

  get 'recommendations' =>"recommendations#index",as: "recommendations"

  get 'discover' =>"songs#discover",as: "discover"

  get 'songs/:id'=> "songs#show", :as => "song"

  post 'songs/rate'=> "songs#rate", :as => "song_rate"

  get 'QuickDeal' => "songs#deal", :as =>"deal"

  post 'recordings/create' =>  "recordings#create" 

  get 'recordings/show_data' =>  "recordings#show_data" 

  get 'recordings/show' =>  "recordings#show" 

  get 'recordings/index' =>  "recordings#index" 

  match "recordings/destroy", to: "recordings#destroy", via: :delete
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  authenticated :user do
    root :to => "songs#search" , :as => "authenticated_root"
  end
  root to: 'visitors#home'
  get "/about" => "visitors#about"
  get "/scroll/:scroll_id" => "users#scroll", as: "scroll"
  get '/profile' => "users#profile"
  get "/performance" => "users#performance"
  get "/headset" =>  "users#headset" 
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'BRAIM', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-left
        %li
          =#link_to "My Profile", profile_path, class: "btn btn-primary btn-nav"
      %ul.nav.navbar-nav.navbar-right
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li
  %p#signalQuality
%li 
  =link_to "#" , class: "navbar-signal-quality" do
    =image_tag "epoc-no-signal.png" , name: "signal_quality"
%li 
  =link_to "#" do
    =image_tag "wireless-no-signal.png" , name: "wireless_quality" 
%li 
  =link_to "#" do
    =image_tag "battery-empty.png" , name: "battery_quality"

%li.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
    =image_tag gravatar_url(current_user), class: "img-responsive mini-thumb header-user-thumb"
    =current_user.full_name
    %b.caret
  %ul.dropdown-menu
    %li
      =link_to "My Profile", profile_path
    %li
      =link_to "Settings", edit_user_registration_path
    %li.divider
    %li
      =link_to "Log out", destroy_user_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %object#plugin0{:height => "0", :type => "application/x-emotivlifesciencesbtle", :width => "0"}
      %param{:name => "onload", :value => "pluginLoaded"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Braim Browser'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Braim Browser'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application' #, "data-turbolinks-track" => true
    = controller_assets
    = csrf_meta_tags
  %body
    #wrapper
      / Sidebar
      #sidebar-wrapper
        %ul.sidebar-nav
          %li.sidebar-brand
            %a{:href => "#"}
              Start Bootstrap
          %li
            =link_to "My Profile", profile_path
          %li
            =link_to "Braim Test", test_path
          %li
            =link_to "Search Music", songs_search_path
          %li
            =link_to "Discover Music", discover_path
          %li
            =link_to "Personalized Recommendations", recommendations_path
          %li
            =link_to "Headset", headset_path
          %li
            =link_to "Performance Metrics", performance_path
          %li
            =link_to "Log out", destroy_user_session_path, method: :delete
      / /#sidebar-wrapper
      / Page Content
      #page-content-wrapper
        .container-fluid
          %header
            = render 'layouts/navigation'
          %main{:role => "main"}
            = render 'layouts/messages'
            = yield
            .bg_load
              .wrapper
              / .inner
              /   %span L
              /   %span o
              /   %span a
              /   %span d
              /   %span i
              /   %span n
              /   %span g

          %canvas#myCanvas{:height => "1000", :style => "border:0px", :width => "500"}
            Your browser does not support the HTML5 canvas tag.

app/views/layouts/visitors.html.haml
!!!
%html
  %head
    %object#plugin0{:height => "0", :type => "application/x-emotivlifesciencesbtle", :width => "0"}
      %param{:name => "onload", :value => "pluginLoaded"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Braim Browser'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Braim Browser'}"}
    = stylesheet_link_tag 'application', media: 'all' 
    = javascript_include_tag 'application' , "data-turbolinks-track" => true
    = controller_assets
    = csrf_meta_tags
  %body
    %header
      -# navigation styled for Bootstrap 3.0
      %nav.navbar.navbar-default.navbar-fixed-top
        .container
          .navbar-header
            %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to 'BRAIM', root_path, class: 'navbar-brand'
          .collapse.navbar-collapse
            %ul.nav.navbar-nav.navbar-right.nav-pills
              %li 
                =link_to "About", about_path 
              %li 
                =link_to "Log in", new_user_session_path, class: "btn btn-primary btn-nav"
              %li 
                =link_to "Sign up", new_user_registration_path, class: "btn btn-success  btn-nav"
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield